"""Word-level (karaoke) lyrics alignment job endpoints and GPU worker reporting."""
import json
from typing import Optional

from fastapi import APIRouter, HTTPException, Body, Query

import db
from services.lyrics_service import (
    gpu_lyrics_executor,
    process_word_lyrics_job,
    queue_word_alignment,
)

router = APIRouter(prefix="/api", tags=["lyrics-alignment"])


@router.post("/tracks/{track_id}/generate-word-lyrics")
async def generate_word_lyrics(
    track_id: str,
    language: Optional[str] = Query(None, description="Язык распознавания: 'ru', 'en' или None"),
    force: bool = Query(False, description="Принудительно пересоздать разметку"),
    refetch: bool = Query(False, description="Заново запросить текст из внешнего источника LRCLIB"),
):
    """
    Queues word-level lyrics alignment on the dedicated GPU executor.
    State survives server restarts in SQLite lyrics_jobs.
    Supports force=True to regenerate existing lyrics, and refetch=True to query LRCLIB again.
    """
    try:
        return queue_word_alignment(track_id, language, force, refetch)
    except LookupError:
        raise HTTPException(status_code=404, detail="Трек не найден в базе данных")
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/tracks/{track_id}/lyrics-generation-status")
def get_lyrics_generation_status(track_id: str):
    """
    Returns the alignment job status from SQLite lyrics_jobs table.
    Survives server restarts!
    """
    job = db.get_lyrics_job(track_id)
    if not job:
        return {"status": "idle"}
    return {
        "status": job.get("status"),
        "stage": job.get("stage"),
        "progress": job.get("progress"),
        "error": job.get("error"),
    }


@router.get("/lyrics-jobs/pending")
def get_pending_lyrics_job():
    """
    Returns the next queued job for external GPU workers (running on workstation with RTX 4070).
    """
    job = db.get_next_pending_lyrics_job()
    if not job:
        return {"job": None}
    return {"job": job}


@router.post("/tracks/{track_id}/lyrics-job-update")
async def update_lyrics_job_status(
    track_id: str,
    payload: dict = Body(...)
):
    """
    Allows GPU worker to report stage, progress, or failure back to the server.
    """
    db.set_lyrics_job(
        track_id,
        status=payload.get("status", "processing"),
        stage=payload.get("stage"),
        progress=payload.get("progress", 0),
        error=payload.get("error")
    )
    return {"ok": True, "track_id": track_id}


@router.post("/tracks/{track_id}/save-word-lyrics")
async def save_word_lyrics(
    track_id: str,
    payload: dict = Body(...)
):
    """
    Saves validated word-level karaoke data generated by the GPU worker.
    """
    word_data = payload.get("word_data")
    if isinstance(word_data, dict):
        word_data_str = json.dumps(word_data, ensure_ascii=False)
    else:
        word_data_str = str(word_data) if word_data is not None else None

    lyrics_source = payload.get("lyrics_source", "lrclib")
    lyrics_status = payload.get("lyrics_status", "word_synced")
    lyrics_language = payload.get("lyrics_language", "ru")
    plain_lyrics = payload.get("lyrics")

    db.update_track_lyrics_data(
        track_id=track_id,
        lyrics=plain_lyrics,
        lyrics_word_data=word_data_str,
        lyrics_source=lyrics_source,
        lyrics_status=lyrics_status,
        lyrics_language=lyrics_language
    )

    db.set_lyrics_job(
        track_id,
        status="completed",
        stage="Готово!",
        progress=100,
        error=None
    )
    return {"ok": True, "track_id": track_id}
