// Styles for TrackEditScreen (extracted from the original 724-line file).
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#22222a',
  },
  backButton: {
    marginRight: 12,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  scrollContent: {
    padding: 16,
  },
  coverSection: {
    alignItems: 'center',
    marginVertical: 12,
  },
  coverImageWrapper: {
    width: 150,
    height: 150,
    borderRadius: 16,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#1c1c22',
    borderWidth: 1,
    borderColor: '#2a2a34',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  coverImage: {
    width: '100%',
    height: '100%',
  },
  coverOverlayBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  coverActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
    gap: 10,
  },
  coverActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: '#16161a',
  },
  coverActionText: {
    fontSize: 13,
    fontWeight: '600',
  },
  coverRevertButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#1c1c22',
  },
  coverRevertText: {
    color: '#8E8E93',
    fontSize: 13,
    fontWeight: '500',
  },
  coverStatusText: {
    fontSize: 12,
    marginTop: 8,
    fontWeight: '600',
  },
  cardSection: {
    backgroundColor: '#121216',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#202028',
    padding: 14,
    marginTop: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: '#8E8E93',
    fontSize: 12,
    marginTop: 3,
    marginBottom: 12,
  },
  fieldsContainer: {
    marginTop: 8,
  },
  label: {
    color: '#8E8E93',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: '#16161c',
    color: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#262630',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 44,
  },
  resultsContainer: {
    backgroundColor: '#16161c',
    borderRadius: 10,
    marginTop: 10,
    padding: 8,
    borderWidth: 1,
    borderColor: '#262630',
  },
  resultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#2a2a36',
  },
  resultsCountText: {
    color: '#8E8E93',
    fontSize: 12,
    fontWeight: '600',
  },
  closeResultsText: {
    color: '#8E8E93',
    fontSize: 12,
  },
  metadataResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#22222a',
  },
  resultThumb: {
    width: 42,
    height: 42,
    borderRadius: 6,
    backgroundColor: '#1c1c22',
    marginRight: 10,
  },
  resultInfo: {
    flex: 1,
  },
  resultTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  resultMeta: {
    color: '#8E8E93',
    fontSize: 12,
    marginTop: 2,
  },
  applyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    marginLeft: 8,
  },
  applyBadgeText: {
    color: '#1c1c1e',
    fontSize: 12,
    fontWeight: '700',
  },
  resultItem: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#22222a',
  },
  textArea: {
    backgroundColor: '#16161c',
    color: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#262630',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    height: 160,
    lineHeight: 18,
  },
  saveButton: {
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveButtonText: {
    color: '#1c1c1e',
    fontSize: 16,
    fontWeight: '700',
  },
});
